# Generated by Django 5.0.6 on 2024-05-27 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handwashingevent',
            name='time_to_dispense_water',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='handwashingevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autowash.userprofile'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='time_to_dispense_water',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)]),
        ),
    ]
