# Generated by Django 5.0.6 on 2024-06-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0002_alter_handwashingevent_time_to_dispense_water_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemstatus',
            name='on_off_button_status',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='machine_status',
            field=models.BooleanField(default=True),
        ),
    ]
