# Generated by Django 5.0.6 on 2024-06-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0004_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menucode', models.IntegerField()),
                ('menuname', models.CharField(max_length=100)),
                ('menutype', models.IntegerField()),
                ('submenuname', models.CharField(max_length=100)),
                ('menulink', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MenuMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menucode', models.IntegerField()),
                ('menuname', models.CharField(max_length=100)),
                ('menutype', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
