# Generated by Django 5.0.6 on 2024-06-10 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0005_menulist_menumain_delete_menuitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuList',
        ),
        migrations.DeleteModel(
            name='MenuMain',
        ),
    ]
