# Generated by Django 5.0.6 on 2024-06-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0006_delete_menulist_delete_menumain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='machine_status',
        ),
        migrations.AddField(
            model_name='handwashingevent',
            name='water_remaining',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='machine_status',
            field=models.BooleanField(default=True),
        ),
    ]
