# Generated by Django 5.0.6 on 2024-07-22 13:19

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0008_userprofile_email_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hands_washed', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('water_dispensed_ml', models.FloatField()),
                ('remaining_water_ml', models.FloatField()),
                ('water_sensor_data', models.JSONField(default=dict)),
                ('ir_sensor_distance_cm', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='systemstatus',
            name='camera_enabled',
        ),
        migrations.RemoveField(
            model_name='systemstatus',
            name='ir_sensor_status',
        ),
        migrations.RemoveField(
            model_name='systemstatus',
            name='machine_status',
        ),
        migrations.RemoveField(
            model_name='systemstatus',
            name='solenoid_valve_status',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ir_sensor_distance_navigation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='ir_sensor_distance_cm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='system_performance',
            field=models.CharField(default='Normal', max_length=255),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='water_leak_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='water_level',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='HandWashingEvent',
        ),
    ]
