# Generated by Django 5.0.7 on 2024-08-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0009_sensordata_remove_systemstatus_camera_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemstatus',
            old_name='water_leak_detected',
            new_name='anomaly_detected',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='ir_sensor_distance_cm',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='water_sensor_data',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='ir_sensor_distance_navigation',
        ),
        migrations.RemoveField(
            model_name='systemstatus',
            name='system_performance',
        ),
        migrations.AddField(
            model_name='sensordata',
            name='ir_sensor_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='anomaly_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='operational_state',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Maintenance Required', 'Maintenance Required')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemstatus',
            name='ultrasonic_distance_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
