# Generated by Django 5.0.7 on 2024-08-21 10:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0013_alter_sensordata_id_alter_systemsettings_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='remaining_water_ml',
            new_name='current_water_volume_ml',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='water_dispensing_volume',
            new_name='water_flow_speed',
        ),
        migrations.RemoveField(
            model_name='systemstatus',
            name='ir_sensor_distance_cm',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='flow_speed',
            field=models.PositiveIntegerField(choices=[(0, '0'), (64, '64'), (85, '85'), (100, '100'), (120, '120'), (128, '128'), (160, '160'), (190, '190'), (220, '220'), (240, '240'), (255, '255')], default=0),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='time_to_dispense_water',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(40)]),
        ),
    ]
