# Generated by Django 5.0.7 on 2024-08-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0014_rename_remaining_water_ml_sensordata_current_water_volume_ml_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='water_dispensed_ml',
            field=models.FloatField(default=0.0),
        ),
    ]
