# Generated by Django 5.0.7 on 2024-08-26 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0015_alter_sensordata_water_dispensed_ml'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensordata',
            name='last_known_volume_ml',
            field=models.FloatField(default=0.0),
        ),
    ]
