# Generated by Django 5.0.7 on 2024-08-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autowash', '0016_sensordata_last_known_volume_ml'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='time_to_dispense_water',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='user',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='water_flow_speed',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='duration',
            field=models.IntegerField(choices=[(5000, '5 seconds'), (10000, '10 seconds'), (15000, '15 seconds'), (20000, '20 seconds'), (25000, '25 seconds'), (30000, '30 seconds'), (35000, '35 seconds'), (40000, '40 seconds')], default=5000, help_text='Select a duration in milliseconds from the predefined choices.', verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='flow_speed',
            field=models.IntegerField(choices=[(0, '0'), (64, '64'), (85, '85'), (100, '100'), (120, '120'), (128, '128'), (160, '160'), (190, '190'), (220, '220'), (240, '240'), (255, '255')], help_text='Select a flow speed from the predefined choices.', verbose_name='Flow Speed'),
        ),
    ]
